save-position-on-quit=yes
watch-later-options=start,aid,sid,sub-delay

vo=gpu-next
# vaapi/nvdec on linux
# auto-safe on windows
hwdec=nvdec

sub-font-size=40
sub-border-size=2
sub-shadow-offset=1

volume=100
volume-max=200

keep-open=yes

screenshot-format=png
screenshot-directory=~/Pictures

