save-position-on-quit=yes
watch-later-options=start,aid,sid

vo=gpu-next
hwdec=nvdec # comment or set vaapi on laptop

sub-font-size=40
sub-border-size=2
sub-shadow-offset=1

volume=100
volume-max=200

keep-open=yes

screenshot-format=png
screenshot-directory=~/Pictures

